### ISSUE TITLE
Ubuntu 21.04 libsodium-dev

### ISSUE THREAD

**Issue by salvatorecorvaglia** [vertices-network/c-vertices-sdk#10]
For the new Ubuntu release (version 21.04), the **libsodium** package is not found, so you need to install the dev package:
`sudo apt-get install libsodium-dev`

**Comment by fouge** [comment]
Thanks @salvatorecorvaglia for letting us know. 
I'll add the instruction in our documentation.

Then, once you've downloaded the dependency, everything went well?

**Comment by salvatorecorvaglia** [comment]
yes, it works perfectly on that version

**Comment by fouge** [comment]
Good to know @salvatorecorvaglia !
